version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db_house
  db_house:
    image: postgres:latest
    environment:
      POSTGRES_DB: house_system_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"